In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import log_loss,confusion_matrix,classification_report,roc_curve,auc

In [2]:
train = pd.read_csv('train.csv')
test=pd.read_csv('testing.csv')
target_col = ['toxic', 'severe_toxic', 'obscene', 'threat','insult', 'identity_hate']


In [3]:
v = TfidfVectorizer()

In [4]:
X_train = v.fit_transform(train['comment_text'])
X_test = v.transform(test['comment_text'])
X_test


<100x189775 sparse matrix of type '<class 'numpy.float64'>'
	with 3779 stored elements in Compressed Sparse Row format>

In [5]:

model=[]
def sed(inp="fuck you asshole"):
    df = pd.DataFrame()
    df = df.append({"toxic":1},ignore_index = True)
    df
    i=0
    for label in ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']:
        y = train[label]
        model.append(LogisticRegression(solver='sag'))
        model[i].fit(X_train, y)
        test[label] = model[i].predict_proba(X_test)[:, 1]
        df[label]=model[i].predict_proba(v.transform([inp]))[:, 1]
        i=i+1
    return df.values
k=sed("Yo bitch Ja Rule is more succesful then you'll ever be whats up with you and hating you sad mofuckas...i should bitch slap ur pethedic white faces ")

In [6]:
y = train[target_col]
test.head(11)

Unnamed: 0                id  \
0            0  00001cee341fdb12   
1            1  0000247867823ef7   
2            2  00013b17ad220c46   
3            3  00017563c3f7919a   
4            4  00017695ad8997eb   
5            5  0001ea8717f6de06   
6            6  00024115d4cbde0f   
7            7  000247e83dcc1211   
8            8  00025358d4737918   
9            9  00026d1092fe71cc   
10          10  0002eadc3b301559   

                                         comment_text     toxic  severe_toxic  \
0   Yo bitch Ja Rule is more succesful then you'll...  0.998338      0.180625   
1   == From RfC == \n\n The title is fine as it is...  0.006603      0.001559   
2   " \n\n == Sources == \n\n * Zawe Ashton on Lap...  0.042323      0.006283   
3   :If you have a look back at the source, the in...  0.003177      0.001640   
4           I don't anonymously edit articles at all.  0.034340      0.003960   
5   Thank you for understanding. I think very high...  0.007496      0.001818   
6   Please do not add nonsense to Wikipedia. Such ...  0.004514      0.000810   
7                    :Dear god this site is horrible.  0.476601      0.005281   
8   " \n Only a fool can believe in such numbers. ...  0.010329      0.001544   
9   == Double Redirects == \n\n When fixing double...  0.005264      0.000882   
10  I think its crap that the link to roggenbier i...  0.175288      0.000378   

     obscene    threat    insult  identity_hate  
0   0.994830  0.046665  0.961528       0.282610  
1   0.004004  0.000423  0.005722       0.003052  
2   0.020711  0.001879  0.023333       0.006021  
3   0.003103  0.001037  0.003710       0.000932  
4   0.011136  0.001650  0.011539       0.003559  
5   0.004079  0.002128  0.008214       0.002092  
6   0.004056  0.000593  0.004356       0.001309  
7   0.051993  0.002139  0.093019       0.007753  
8   0.008374  0.000929  0.005574       0.002345  
9   0.005191  0.000827  0.005283       0.001262  
10  0.058233  0.000333  0.006487       0.001791

In [7]:

"""for col in target_col:
  print("Column:",col)
  pred_pro = model.predict_proba(X_train)[:,1]
  frp,trp,thres = roc_curve(y[col],pred_pro)
  auc_val =auc(frp,trp)
  print(auc_val)"""

'for col in target_col:\n  print("Column:",col)\n  pred_pro = model.predict_proba(X_train)[:,1]\n  frp,trp,thres = roc_curve(y[col],pred_pro)\n  auc_val =auc(frp,trp)\n  print(auc_val)'

In [8]:
k

array([[0.99029015, 0.1196628 , 0.96723607, 0.04600583, 0.9481792 ,
        0.18835909]])

In [9]:

"""prd_1 = pd.DataFrame(test,columns=target_col)
submit = pd.concat([test['id'],prd_1],axis=1)
#submit.to_csv('toxic_lr.csv.gz',compression='gzip',index=False)
submit.to_csv('toxic_lr.csv',index=False)
submit.head()"""

"prd_1 = pd.DataFrame(test,columns=target_col)\nsubmit = pd.concat([test['id'],prd_1],axis=1)\n#submit.to_csv('toxic_lr.csv.gz',compression='gzip',index=False)\nsubmit.to_csv('toxic_lr.csv',index=False)\nsubmit.head()"

In [10]:
lis=[]
inp="fuck you asshole"
for i in range(6):
    lis.append(model[i].predict_proba(v.transform([inp]))[:, 1])

In [11]:
lis

[array([0.99999995]),
 array([0.93159643]),
 array([0.99999999]),
 array([0.0195166]),
 array([0.99991116]),
 array([0.05889025])]

In [12]:
import dill as pickle
f=open("final_model.pkl", "wb")
pickle.dump(model,f)
pickle.dump(v,f)
